version: "3.8"

services:
    proxy:
        ports:
            - 8081:80

    api:
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB_NAME}
            POSTGRES_HOST: ${PG_HOST}
            POSTGRES_PORT: ${PG_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            PROXY_SERVER_ADDR: ${PROXY_SERVER}
            ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_SECRET}
            REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_SECRET}
            TOKEN_ISSUER: ${TOKEN_ISSUER}
        ports:
            - 58080:8080

    postgres:
        ports:
            - 54320:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB_NAME}
    
    pgadmin:
        ports:
            - 54330:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN}
            PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}

    redis:
        ports:                  
            - "56379:6379"
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: redis-server --requirepass ${REDIS_PASSWORD}
