FROM nginx:latest

WORKDIR /app
# RUN mkdir ./build
# ADD ./build ./build
RUN rm /etc/nginx/nginx.conf
# RUN rm /etc/nginx/conf.d/default.conf
COPY ./server.conf /etc/nginx/conf.d/
COPY ./nginx.conf /etc/nginx/

# 80 포트 오픈
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]