FROM nginx:latest

WORKDIR /app
RUN rm /etc/nginx/nginx.conf
COPY ./server.conf /etc/nginx/conf.d/
COPY ./nginx.conf /etc/nginx/

# 80 포트 오픈
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# FROM code-wave-react:1.1.0 as builder

# COPY --from=builder /app/build /app/build